//! Translation `.wasm` pack — the hand-split, on-demand i18n payload for the
//! rusterando frontend.
//!
//! WHY a separate crate / wasm: the main hydrate bundle ships German only. All
//! non-German translations live HERE and are fetched once, cached by content
//! hash, and loaded into the browser on demand (see scripts/build-i18n-pack.sh
//! + the i18n-loader.js loader). This keeps the main bundle lean and lets the
//! translation payload load/unload live. See feedback_i18n_db_first_wasm_overlay.
//!
//! Resolution model (DB-first): the DB is always served first; this pack only
//! FILLS empty cells. The frontend asks the pack for a string only when the DB
//! has no value for the active locale. The pack never overrides the DB.
//!
//! DATA REPRESENTATION (tuned): the translation data is NOT parsed from JSON at
//! runtime — `build.rs` bakes it into sorted `&'static [(locale, key, value)]`
//! slices (see $OUT_DIR/i18n_data.rs), looked up by binary search. This removes
//! serde_json + the HashMap from the wasm entirely (~45 KB of the old 73 KB
//! served), with zero parse/alloc at runtime. The build-time JSON
//! (generated/*.json) stays the source artifact the builder writes.
//!
//! Two data categories, both keyed for direct lookup:
//!   * chrome — fixed UI strings, keyed by dotted namespace key
//!     (e.g. "menu.add_to_cart").
//!   * menu   — menu vocabulary, keyed by the GERMAN SOURCE string
//!     (e.g. "mit Tomaten und Mozzarella").

use wasm_bindgen::prelude::*;

// CHROME / MENU: &[(locale, key, value)] sorted by (locale, key).
// LOCALES: &[&str].  PACK_HASH: &str.  All generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/i18n_data.rs"));

/// Binary-search a sorted `(locale, key, value)` table for `(locale, key)`.
/// O(log n), no allocation. The table is sorted by `(locale, key)` (build.rs
/// emits BTreeMap iteration order), matching this comparison.
fn find<'a>(table: &'a [(&'a str, &'a str, &'a str)], locale: &str, key: &str) -> Option<&'a str> {
    table
        .binary_search_by(|(l, k, _)| (*l, *k).cmp(&(locale, key)))
        .ok()
        .map(|i| table[i].2)
}

// ---------------------------------------------------------------------------
// Public lookup core (plain Rust — unit-testable natively, no wasm needed).
// ---------------------------------------------------------------------------

/// Chrome lookup: dotted key in the active locale. `None` if absent (caller
/// falls back to German).
pub fn lookup_chrome(locale: &str, key: &str) -> Option<&'static str> {
    find(CHROME, locale, key)
}

/// Menu lookup: keyed by the GERMAN SOURCE string. `None` if absent.
pub fn lookup_menu(locale: &str, german_source: &str) -> Option<&'static str> {
    find(MENU, locale, german_source)
}

/// The locales this pack carries (sorted).
pub fn locales() -> &'static [&'static str] {
    LOCALES
}

// ---------------------------------------------------------------------------
// wasm-bindgen surface (what the loaded module exposes to JS / the main wasm).
// ---------------------------------------------------------------------------

/// Chrome string for `key` in `locale`, or empty string if absent. (JS can't
/// receive `Option`; empty string == "not in pack, fall back".)
#[wasm_bindgen]
pub fn lookup(locale: &str, key: &str) -> String {
    lookup_chrome(locale, key).unwrap_or_default().to_string()
}

/// Menu translation for the German `source` in `locale`, or empty if absent.
#[wasm_bindgen]
pub fn menu_lookup(locale: &str, source: &str) -> String {
    lookup_menu(locale, source).unwrap_or_default().to_string()
}

/// JSON array of the locales in this pack, e.g. `["en","it"]`. Hand-built (no
/// serde) so the wasm stays parser-free.
#[wasm_bindgen]
pub fn pack_locales() -> String {
    let mut s = String::from("[");
    for (i, l) in LOCALES.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        s.push('"');
        s.push_str(l);
        s.push('"');
    }
    s.push(']');
    s
}

/// The pack's content-hash stamp (diagnostics).
#[wasm_bindgen]
pub fn pack_hash() -> String {
    PACK_HASH.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_non_empty() {
        assert!(!CHROME.is_empty(), "CHROME table empty");
        assert!(!MENU.is_empty(), "MENU table empty");
        assert!(!LOCALES.is_empty(), "LOCALES empty");
    }

    #[test]
    fn tables_are_sorted_for_binary_search() {
        // The lookups rely on (locale, key) sort order. Guard it so a future
        // generator change can't silently break binary_search.
        for table in [CHROME, MENU] {
            for w in table.windows(2) {
                let a = (w[0].0, w[0].1);
                let b = (w[1].0, w[1].1);
                assert!(a <= b, "table not sorted: {a:?} > {b:?}");
            }
        }
    }

    #[test]
    fn lookups_resolve_or_none() {
        assert!(lookup_chrome("zz", "menu.add_to_cart").is_none());
        assert!(lookup_menu("zz", "mit Tomaten und Mozzarella").is_none());
    }

    #[test]
    fn fat_default_resolves_known_strings() {
        assert_eq!(lookup_chrome("en", "menu.add_to_cart"), Some("Add to cart"));
        assert_eq!(
            lookup_menu("en", "mit Tomaten und Mozzarella"),
            Some("with tomatoes and mozzarella")
        );
        // German is never in the pack (it's the DB/base).
        assert!(lookup_chrome("de", "menu.add_to_cart").is_none());
    }

    #[test]
    fn all_seven_locales_present_for_menu() {
        let src = "mit Tomaten und Mozzarella";
        for loc in ["en", "fr", "it", "es", "pt", "ru", "cn"] {
            assert!(
                lookup_menu(loc, src).is_some(),
                "menu locale '{loc}' missing translation for {src:?}"
            );
        }
    }

    #[test]
    fn wasm_surface_empty_string_on_miss() {
        assert_eq!(lookup("zz", "nope.key"), "");
        assert_eq!(menu_lookup("zz", "nope"), "");
        assert!(pack_locales().starts_with('['));
        assert!(!pack_locales().is_empty());
    }
}
