-- Shop-contact data lives in app_settings as `shop_*` keys. Read at
-- server boot into a BrandingHandle (mirroring ThemeHandle), edited via
-- /admin/branding. Default values are placeholders so a fresh fork
-- doesn't ship anyone else's phone number.

INSERT OR IGNORE INTO app_settings (key, value, label_de, hint_de) VALUES
  ('shop_name',           'Mein Restaurant',
                          'Name',
                          'Erscheint im Header, in E-Mails, auf der PDF-Speisekarte, im Impressum.'),
  ('shop_phone',          '',
                          'Telefon',
                          'Servicenummer für Kunden-Anrufe.'),
  ('shop_email',          '',
                          'E-Mail',
                          'Kontakt-Adresse für Impressum + Kunden-Emails (NICHT der SMTP-Sender — das ist EMAIL_FROM).'),
  ('shop_owner',          '',
                          'Inhaber',
                          'Vor- und Zuname für das Impressum (TMG §5).'),
  ('shop_address_street', '',
                          'Straße',
                          'Straße + Hausnummer für das Impressum.'),
  ('shop_address_plz_city','',
                          'PLZ + Ort',
                          'PLZ und Stadt zusammen, z.B. \"12345 Musterstadt\".'),
  ('shop_city',           '',
                          'Stadt',
                          'Stadt-Name allein, für Lieferradius-Validierung.'),
  ('shop_lat',            '0',
                          'Breitengrad',
                          'Geographische Breite des Ladens (für Tour-Optimierung).'),
  ('shop_lon',            '0',
                          'Längengrad',
                          'Geographische Länge des Ladens.'),
  ('shop_vat_id',         '',
                          'USt-IdNr.',
                          'EU-Umsatzsteuer-Identifikationsnummer (Kleinunternehmer können das Feld leer lassen).'),
  ('shop_tax_rate',       '7',
                          'Steuersatz %',
                          'Mehrwertsteuer-Satz, der auf der Rechnung erscheint (DE: 7 für reduzierten Satz, 19 für Standardsatz).'),
  ('shop_bank_name',      '',
                          'Bank',
                          'Optional, erscheint auf Rechnungen mit Überweisungs-Option.'),
  ('shop_bank_iban',      '',
                          'IBAN',
                          'Optional.'),
  ('shop_bank_bic',       '',
                          'BIC',
                          'Optional.');
