//! Build-time codegen: turn `{ locale: { key: value } }` JSON into sorted
//! `&'static [..]` Rust slices, written to a consumer's `$OUT_DIR` for
//! `include!`. The consumer's runtime then looks up by binary search — no JSON
//! parser in the wasm.
//!
//! Used from a `build.rs` (enable the `build` feature on this crate as a
//! `[build-dependencies]`). Example:
//!
//! ```ignore
//! // build.rs
//! fn main() {
//!     let mut g = rusterando_wasm_split::build::Codegen::new();
//!     g.full_table("CHROME", "../some/chrome.json");   // (locale, key, value)
//!     g.key_table("COVERAGE", "../some/menu.json");    // (locale, key) only
//!     g.locales_union("LOCALES", &["../some/chrome.json", "../some/menu.json"]);
//!     g.literal_str("PACK_HASH", "../some/hash.txt");
//!     g.write("data.rs"); // → $OUT_DIR/data.rs ; include! it in lib.rs
//! }
//! ```

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::Path;

type Table = BTreeMap<String, BTreeMap<String, String>>;

/// Accumulates generated Rust source, then writes it to `$OUT_DIR`.
pub struct Codegen {
    out: String,
}

impl Default for Codegen {
    fn default() -> Self {
        Self::new()
    }
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            out: String::from("// @generated by rusterando-wasm-split::build — do not edit.\n\n"),
        }
    }

    /// Parse a `{ locale: { key: value } }` JSON file (BTreeMap → deterministic,
    /// already sorted by locale then key — exactly the binary-search order).
    /// Emits a `cargo:rerun-if-changed` so the consumer rebuilds on data change.
    fn load(path: &str) -> Table {
        println!("cargo:rerun-if-changed={path}");
        let raw = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("wasm-split build: read {path}: {e}"));
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("wasm-split build: parse {path}: {e}"))
    }

    /// `pub static NAME: &[(&str, &str, &str)]` = sorted (locale, key, value).
    /// Empty values are kept (chrome wants them); use `key_table` to drop them.
    pub fn full_table(&mut self, name: &str, json_path: &str) -> &mut Self {
        let data = Self::load(json_path);
        self.out
            .push_str(&format!("pub static {name}: &[(&str, &str, &str)] = &[\n"));
        for (locale, table) in &data {
            for (key, value) in table {
                self.out.push_str(&format!(
                    "    (\"{}\", \"{}\", \"{}\"),\n",
                    esc(locale),
                    esc(key),
                    esc(value)
                ));
            }
        }
        self.out.push_str("];\n\n");
        self
    }

    /// `pub static NAME: &[(&str, &str)]` = sorted (locale, key) — the SET of
    /// keys with a non-empty value (for coverage / membership tests). Values are
    /// dropped.
    pub fn key_table(&mut self, name: &str, json_path: &str) -> &mut Self {
        let data = Self::load(json_path);
        self.out
            .push_str(&format!("pub static {name}: &[(&str, &str)] = &[\n"));
        for (locale, table) in &data {
            for (key, value) in table {
                if value.trim().is_empty() {
                    continue;
                }
                self.out
                    .push_str(&format!("    (\"{}\", \"{}\"),\n", esc(locale), esc(key)));
            }
        }
        self.out.push_str("];\n\n");
        self
    }

    /// `pub static NAME: &[&str]` = sorted union of the top-level locale keys
    /// across the given JSON files.
    pub fn locales_union(&mut self, name: &str, json_paths: &[&str]) -> &mut Self {
        let mut set: BTreeSet<String> = BTreeSet::new();
        for p in json_paths {
            for k in Self::load(p).keys() {
                set.insert(k.clone());
            }
        }
        self.out
            .push_str(&format!("pub static {name}: &[&str] = &[\n"));
        for l in &set {
            self.out.push_str(&format!("    \"{}\",\n", esc(l)));
        }
        self.out.push_str("];\n\n");
        self
    }

    /// `pub static NAME: &str` = the trimmed contents of a small text file
    /// (e.g. a hash stamp). Missing file → `"dev"`.
    pub fn literal_str(&mut self, name: &str, path: &str) -> &mut Self {
        println!("cargo:rerun-if-changed={path}");
        let v = fs::read_to_string(path)
            .map(|s| s.trim().to_string())
            .unwrap_or_else(|_| "dev".to_string());
        self.out
            .push_str(&format!("pub static {name}: &str = \"{}\";\n\n", esc(&v)));
        self
    }

    /// Write the accumulated source to `$OUT_DIR/<file>`.
    pub fn write(&self, file: &str) {
        let dest = Path::new(&env::var("OUT_DIR").unwrap()).join(file);
        fs::write(&dest, &self.out).unwrap();
    }
}

/// Escape a string for a Rust `"..."` literal.
fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
